### ISSUE TITLE
vspk-ansible support for 6.0.Rx

### ISSUE THREAD

**Issue by marcowenwolf** [nuagenetworks/vspk-ansible#8]
Does vspk-ansible support Nuage release6.0.Rx?

**Comment by pdellaert** [comment]
@marcowenwolf yes, just use `api_version: v6`. Of course, i strongly suggest to use the nuage_vspk Ansible module that is provided in native Ansible, this repo is no longer maintained and all maintenance happens on the Ansible repository itself.
